substitutions:
  # ref: https://docs.m5stack.com/en/atom/Atomic_Audio-3.5_Base#compatible
  # These are the pins used by the AtomS3-Lite
  # You should redefine them regardless as I may change my mind what I want to use by default
  audio_base_pin_scl: GPIO39
  audio_base_pin_sda: GPIO38
  audio_base_pin_din: GPIO5
  audio_base_pin_lrck: GPIO6
  audio_base_pin_dout: GPIO7
  audio_base_pin_sck: GPIO8

external_components:
  # I couldn't find mention of this in m5stack's docs, but I found it somewhere online and it made things work.
  # Without this, the amp turned on and silent/static came out during playback, but no actual audio
  # See https://github.com/m5stack/esphome-yaml/tree/main/components/es8311 for info
  # FIXME: Can I remove this and just set `use_mclk: false`? Looks like that's already set
  - source: github://m5stack/esphome-yaml/components@main
    components: [es8311]
    refresh: 1d
  # https://github.com/esphome/esphome/pull/14389
  - id: upstream_pr_snapclient
    source: github://pr#14389
    components: [ snapclient, media_player ]
    refresh: 1d
  # - id: upstream_pr_snapclient
  #   source: github://mijofa/esphome-luar123-snapclient@snapclient2
  #   components: [ snapclient, media_player ]
  #   refresh: 0s

# ============================================================================
# ESP32 Hardware Configuration
# ============================================================================
esp32:
  framework:
    type: esp-idf

### i2c/i2s communication bus
i2c:
  - id: audio_base_i2c_bus
    sda: "${audio_base_pin_sda}"
    scl: "${audio_base_pin_scl}"
i2s_audio:
  - id: audio_base_i2s_audio
    i2s_lrclk_pin: "${audio_base_pin_lrck}"
    i2s_bclk_pin: "${audio_base_pin_sck}"
### Speaker Enable switch
# The audio base uses a pin extender for just 1 single pin.
# Mostly because they've designed the Atom connector pins with not much space for anything but the i2s/i2c bus.
# FIXME: Consider marking this internal and always on.
# FIXME: Can we switch this on/off from firmware when snapcast mutes/unmutes?
pi4ioe5v6408:
  - id: audio_base_pi4ioe5v6408
    i2c_id: audio_base_i2c_bus
    address: 0x43
switch:
  - platform: gpio
    # Note this affects ONLY the internal speaker, not the dac itself or 3.5 output.
    # Making it effectively useless in most situations
    id: audio_base_speaker_enable
    pin:
      pi4ioe5v6408: audio_base_pi4ioe5v6408
      number: 0
      mode:
        output: true
    # We deal with this internally, Home Assistant doesn't need to know about it
    internal: true
    restore_mode: ALWAYS_OFF

### Audio DAC for volume control
# This DAC is what's causing the loud pop when silent for a bit
audio_dac:
  - platform: es8311
    id: es8311_dac
    i2c_id: audio_base_i2c_bus
    bits_per_sample: 16bit
    sample_rate: "${audio_base_sample_rate}"
    use_microphone: false
    use_mclk: false

# Uncomment this section for snapcast instead of sendspin
media_player:
  - platform: snapclient
    # Don't show up in Home Assistant, because Home Assistant can't really do anything with it anyway.
    # FIXME: Is it possible to associate the snapcast player with this device?
    internal: true
    id: snapclient_media_player
    hostname: ${snapserver_hostname}
    # port: 1704  # default
    # name: ${friendly_name}
    # # FIXME: This pin ONLY affects the internal speaker, not the dac itself.
    # mute_pin:
    #   pi4ioe5v6408: pi4ioe5v6408_hub
    #   number: 0
    #   mode:
    #     output: true
    # audio_dac: es8311_dac
    i2s_dout_pin: "${audio_base_pin_din}"
    on_play:
      - logger.log: "Playback started!"
      - audio_dac.mute_off:
          id: es8311_dac
      - audio_dac.set_volume:
          id: es8311_dac
          # I've seen indication that I should sit between 0.5 & 0.8, so let's split the difference and go with 0.65
          volume: 65%
      - switch.turn_on: audio_base_speaker_enable
    on_pause:
      - logger.log: "Playback paused!"
      - audio_dac.mute_on:
          id: es8311_dac
      - switch.turn_off: audio_base_speaker_enable
    on_idle:
      - logger.log: "Playback finished!"
      - audio_dac.mute_on:
          id: es8311_dac
      - switch.turn_off: audio_base_speaker_enable
    # on_state:
    #   # FIXME: I would like to somehow flip a binary sensor or change an LED colour when the player is muted/unmuted.
    #   #        Is this even possible?
    #   - logger.log: "Playback State change!"
