substitutions:
  # ref: https://docs.m5stack.com/en/atom/Atomic%20SPK%20Base#compatible
  # These are the pins used by the AtomS3-Lite
  # You should redefine them regardless as I may change my mind what I want to use by default
  spk_base_pin_lrclk: GPIO39
  spk_base_pin_data: GPIO38
  spk_base_pin_bclk: GPIO5
  # # I'm not actually using these (currently?) as they are intended for the SD card slot
  # spk_base_pin_spi_mosi: GPIO6
  # spk_base_pin_spi_clk: GPIO7
  # spk_base_pin_spi_miso: GPIO8

  # FIXME: Can I make this into a runtime configurable select entity in Home Assistant?
  spk_base_channel: mono
  spk_base_sample_rate: 32000  # DO NOT CHANGE without also updating the silent flac file as needed
  sendspin_use_psram: false
  sendspin_buffer_size: 25000

# ============================================================================
# ESP32 Hardware Configuration
# ============================================================================
esp32:
  framework:
    # NOTE: Requires this framework... I don't remember why
    type: esp-idf

### i2s communication bus
# Main ref: https://community.home-assistant.io/t/solved-esphome-media-player-with-m5stack-spk-kit-and-atoms3-lite/784663
i2s_audio:
  - id: spk_base_i2s_audio
    i2s_lrclk_pin: "${spk_base_pin_lrclk}"
    i2s_bclk_pin: "${spk_base_pin_bclk}"

### Speaker output
speaker:
  # This is the actual audio output of the audio base itself
  - platform: i2s_audio
    id: spk_base_i2s_speaker
    i2s_audio_id: spk_base_i2s_audio
    i2s_dout_pin: "${spk_base_pin_din}"
    sample_rate: "${spk_base_sample_rate}"
    channel: "${spk_base_channel}"

### Media player inputs
sendspin:
  # The sendspin hub itself, we can't use sendspin without it
  id: sendspin_hub
  task_stack_in_psram: "${sendspin_use_psram}"

media_source:
  - platform: sendspin
    id: media_source_sendspin
    task_stack_in_psram: "${sendspin_use_psram}"
    buffer_size: "${sendspin_buffer_size}"
    sample_rate: "${spk_base_sample_rate}"
media_player:
  # Actually play sound from Sendspin
  - platform: speaker_source
    id: media_player_sendspin
    # No point showing this to Home Assistant because Music Assistant will do that for us.
    # FIXME: Can I have Home Assistant combine the ESPHome device with the Music Assistant one?
    internal: true
    # This spk base has an amplifier, not a dac, so I assume reducing the volume range is not a good idea
    # # FIXME: These numbers were used by m5stack upstream, are they reasonable?
    # volume_min: 0.5
    # volume_max: 0.8
    media_pipeline:
      speaker: spk_base_i2s_speaker
      format: FLAC
      sample_rate: "${spk_base_sample_rate}"
      num_channels: "1"
      sources:
        - media_source_sendspin
